### ISSUE TITLE
ToDo board

### ISSUE THREAD

**Issue by Cheatoid** [StyledStrike/starfall-wingui#1]
# WinGUI TODO

## "Easy"
- [ ] Make `Window` remember position before maximize, to allow restoring back to original position instead of being moved to top-left
- [ ] Make `Window` stay in position when cursor position is not within screen bounds instead of being moved to top-left (tip: `render.cursorPos()` will return nil)
- [ ] Add convenience `SetPos(x, y)` and `SetSize(w, h)` functions to `Panel` (accept `nil`, if provided then don't change a given value)
- [ ] Add `Panel.enabled` field to be able to disable any control (grey out)
- [ ] Add `Panel.opacity` field to be able to set different alpha color (0-255) for any control
- [ ] Add `ComboBox:SetContentAlignment` function to be able to align text to the left/center/right (just like `Button:SetContentAlignment(alignment, padding)`)
- [x] Add `Window:Maximize` and `Window:Restore` functions, for programmatically maximizing/restoring the window
    - `window:SetMaximized( boolean )`
- [ ] Add `ComboBox:RemoveOption` and `SimpleList:RemoveLine` functions, also add `Clear` to remove all items
- [ ] Pass the control itself as the first argument to all interaction events (such as `Button.OnClick`, `ComboBox.OnSelect`, etc)
- [ ] Don't unfocus the currently focused window when pressing E/`+use` outside of screen bounds (only unfocus if cursor is within the screen bounds)

## "Advanced"
- [ ] Fix crash when calling `Clear` function on the empty `VScrollPanel` control
    <details>
    <summary>(click here to expand details)</summary>

    ```lua
    --@client
    --@include wingui.txt
    local WinGUI = require( "wingui.txt" )
    WinGUI:EnableScreenMode()
    local window = WinGUI:Create( "Window" )
    window.w = 256
    window.h = 256
    window:Center()
    window:MakePopup()
    local scrollPanel = WinGUI:Create( "VScrollPanel", window )
    scrollPanel:Dock( WinGUI.DOCK.FILL )
    scrollPanel:Clear()
    hook.add( "render", "", function()
      WinGUI:Render()
    end )
    ```

    ```
    Hook 'think' errored with: SF:wingui.txt:1567: attempt to call method 'SetCanvas' (a nil value)
    stack traceback:
      SF:wingui.txt:1567: in function 'PerformLayout'
      SF:wingui.txt:432: in function 'UpdateLayout'
      SF:wingui.txt:438: in function 'UpdateLayout'
      SF:wingui.txt:438: in function 'UpdateLayout'
      SF:wingui.txt:483: in function 'Think'
    ```
    </details>
- [ ] Fix `Window` not using `w`/`h` values when updated within `render` hook
    <details>
    <summary>(click here to expand details)</summary>

    This should resize the main window to max screen resolution, but it does not. Also children controls get messed up when resizing such window, not sure why.
    ```lua
    --@client
    --@include wingui.txt
    local WinGUI = require("wingui.txt")
    WinGUI:EnableScreenMode()
    local window = WinGUI:Create( "Window" )
    window.w = 300
    window.h = 200
    window:Center()
    window:MakePopup()
    local scrollPanel = WinGUI:Create( "VScrollPanel", window )
    scrollPanel:Dock( WinGUI.DOCK.FILL )
    for i = 1, 20 do
      local button = scrollPanel:Add( "Button" )
      button.text = "Button #" .. i
      button:Dock( WinGUI.DOCK.TOP )
    end
    scrollPanel:SizeToChildren()
    hook.add( "render", "", function()
      local scrW, scrH = render.getResolution()
      window.w = scrW
      window.h = scrH
      window:InvalidateLayout()
      WinGUI:Render()
    end )
    ```
    </details>
- [ ] Implement `RadioButton` control ([ref](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/radiobutton-control-overview-windows-forms))
- [ ] Implement `OnPaint` and `OnMouseHover` events, to allow users to style controls to their desire (custom themes/materials, etc)
- [ ] Implement `Window.zOrder` field which would allow users to get/set Z order of the window (a number indicating whether window is top/bottom-most, in regards to others; typically each `Window` instance should have it's own number, multiple windows can't share the same Z order; a window is either above or below the other window)
- [ ] Implement `WinGUI:GetRootPanel` function (would be useful to easily iterate whole hierarchy of created controls)
    * With above implemented, perhaps introduce `Taskbar` control and add minimize functionality to `Window`
